// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ResetCore.NAsset
{
    
    
    public class R
    {
        
        public static string none_ResourcesList = "none###ResourcesList";
        
        public static string none_New_Material = "none###New Material";
        
        public static string none_StreamingList = "none###StreamingList";
        
        public static string cube_Cube = "cube###Cube";
        
        public static string cube_New_Material = "cube###New Material";
    }
}
